spring:
  application:
    name: codemart_back_java
  datasource:
    url: jdbc:mysql://localhost:3306/codemart?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123123
  data:
    redis:
      port: 6379
      lettuce:
        pool:
          max-wait: 8
          max-active: 8
          min-idle: 1
  neo4j:
    security:
      hostname-verification-enabled: false
server:
  port: 9090