-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 10:28:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codemart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codemart
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `codemart` DEFAULT CHARACTER SET utf8 ;
USE `codemart` ;

-- -----------------------------------------------------
-- Table `codemart`.`system_user_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_user_login` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_user_login` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(200) DEFAULT '未命名用户',
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`system_user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_user_info` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `birthday` DATETIME NULL,
  `register_time` DATETIME NOT NULL DEFAULT current_timestamp(),
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `u_id_idx` (`u_id` ASC) VISIBLE,
  CONSTRAINT `u_login_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `codemart`.`system_user_login` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`system_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_role` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`system_use_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_use_role` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_use_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `u_id_idx` (`u_id` ASC) VISIBLE,
  CONSTRAINT `u_role_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `codemart`.`system_user_info` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_u_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `codemart`.`system_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`system_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_permissions` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_permissions` (
  `per_id` INT NOT NULL AUTO_INCREMENT,
  `per_page` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`system_role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_role_permission` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_role_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `per_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `per_id_idx` (`per_id` ASC) VISIBLE,
  CONSTRAINT `per_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `codemart`.`system_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_per_id`
    FOREIGN KEY (`per_id`)
    REFERENCES `codemart`.`system_permissions` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`sku_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`sku_info` ;

CREATE TABLE IF NOT EXISTS `codemart`.`sku_info` (
  `sku_id` INT NOT NULL AUTO_INCREMENT,
  `sku_name` VARCHAR(45) NULL,
  PRIMARY KEY (`sku_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`demand_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`demand_info` ;

CREATE TABLE IF NOT EXISTS `codemart`.`demand_info` (
  `de_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `person` INT DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp(),
  `operate_time` DATETIME NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`de_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`demand_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`demand_sku` ;

CREATE TABLE IF NOT EXISTS `codemart`.`demand_sku` (
    `ds_id` INT NOT NULL AUTO_INCREMENT,
    `de_id` INT NOT NULL,
    `sku_id` INT NOT NULL,
    PRIMARY KEY (`ds_id`),
    INDEX `ds_id_idx` (`ds_id` ASC) VISIBLE,
    CONSTRAINT `ds_sku_id`
      FOREIGN KEY (`sku_id`)
      REFERENCES `codemart`.`sku_info` (`sku_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `sku_de_id`
    FOREIGN KEY (`de_id`)
    REFERENCES `codemart`.`demand_info` (`de_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `codemart`.`demand_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`demand_detail` ;

CREATE TABLE IF NOT EXISTS `codemart`.`demand_detail` (
  `dd_id` INT NOT NULL AUTO_INCREMENT,
  `de_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `money` DOUBLE NULL,
  `term_day` INT NULL,
  PRIMARY KEY (`dd_id`),
  INDEX `de_id_idx` (`de_id` ASC) VISIBLE,
  INDEX `author_id_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `author_de_id`
    FOREIGN KEY (`de_id`)
    REFERENCES `codemart`.`demand_info` (`de_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `de_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `codemart`.`system_user_info` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`plan_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`plan_info` ;

CREATE TABLE IF NOT EXISTS `codemart`.`plan_info` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  `plan_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`system_user_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`system_user_sku` ;

CREATE TABLE IF NOT EXISTS `codemart`.`system_user_sku` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `sku_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `u_id_idx` (`u_id` ASC) VISIBLE,
  INDEX `sku_id_idx` (`sku_id` ASC) VISIBLE,
  CONSTRAINT `sku_u_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `codemart`.`system_user_info` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `u_sku_id`
    FOREIGN KEY (`sku_id`)
    REFERENCES `codemart`.`sku_info` (`sku_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`user_demand_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`demand_plan` ;

CREATE TABLE IF NOT EXISTS `codemart`.`demand_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `de_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `de_id_idx` (`de_id` ASC) VISIBLE,
  INDEX `plan_id_idx` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `plan_user_de_id`
    FOREIGN KEY (`de_id`)
    REFERENCES `codemart`.`demand_info` (`de_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_de_plan_id`
    FOREIGN KEY (`plan_id`)
    REFERENCES `codemart`.`plan_info` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codemart`.`demand_contenxt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codemart`.`demand_contenxt` ;

CREATE TABLE IF NOT EXISTS `codemart`.`demand_contenxt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `de_id` INT NOT NULL,
  `de_context` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `de_id_idx` (`de_id` ASC) VISIBLE,
  CONSTRAINT `context_de_id`
    FOREIGN KEY (`de_id`)
    REFERENCES `codemart`.`demand_info` (`de_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `codemart`.`demand_status`;

CREATE TABLE IF NOT EXISTS `codemart`.`demand_status` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `de_id` INT NOT NULL,
    `status_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `de_id_idx` (`de_id` ASC) VISIBLE,
    INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
    CONSTRAINT `status_de_id`
        FOREIGN KEY (`de_id`)
        REFERENCES `codemart`.`demand_info` (`de_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `de_status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `codemart`.`demand_status_info` (`status_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

DROP TABLE IF EXISTS `codemart`.`demand_status_info`;

CREATE TABLE `codemart`.`demand_status_info` (
     `status_id` INT NOT NULL AUTO_INCREMENT,
     `status_name` VARCHAR(255) NOT NULL,
     PRIMARY KEY (`status_id`),
     INDEX `status_id_idx` (`status_id` ASC)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `codemart`.`demand_user_info`;

CREATE TABLE `codemart`.`demand_user_info`(
    `dui_id` INT NOT NULL AUTO_INCREMENT,
    `u_id` INT NOT NULL,
    `de_id` INT NOT NULL,
    `join_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (`dui_id`),
    CONSTRAINT `user_join_demand`
    FOREIGN KEY (`u_id`)
        REFERENCES `codemart`.`system_user_login` (`u_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `demand_user_join`
    FOREIGN KEY (`de_id`)
        REFERENCES `codemart`.`demand_info` (`de_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

DROP TABLE IF EXISTS `codemart`.`demand_user_status_info`;

CREATE TABLE `codemart`.`demand_user_status_info`(
     `status_id` INT NOT NULL AUTO_INCREMENT,
     `status_name` VARCHAR(200) NOT NULL,
     PRIMARY KEY (status_id)
)ENGINE = InnoDB;

DROP TABLE IF EXISTS `codemart`.`demand_user_status`;

CREATE TABLE `codemart`.`demand_user_status`(
    `dus_id` INT NOT NULL AUTO_INCREMENT,
    `dui_id` INT NOT NULL,
    `status_id` INT NOT NULL DEFAULT 1,
    PRIMARY KEY (`dus_id`),
    CONSTRAINT `d_u_s`
    FOREIGN KEY (`dui_id`)
        REFERENCES `codemart`.`demand_user_info` (`dui_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `u_d_s`
    FOREIGN KEY (`status_id`)
        REFERENCES `codemart`.`demand_user_status_info` (`status_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

DROP TABLE IF EXISTS `codemart`.`demand_select_of_dibs`;
CREATE TABLE `codemart`.`demand_select_of_dibs`(
    `dsod_id` INT NOT NULL AUTO_INCREMENT,
    `u_id` INT NOT NULL,
    `de_id` INT NOT NULL,
    PRIMARY KEY (`dsod_id`),
    CONSTRAINT `dsod_u_de`
    FOREIGN KEY (`u_Id`)
        REFERENCES `codemart`.`system_user_info` (`u_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `u_de_dsod`
    FOREIGN KEY (`de_id`)
        REFERENCES `codemart`.`demand_info` (`de_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
